### ISSUE TITLE
Some stuff not pulling from the lang files?

### ISSUE THREAD

**Issue by sirkerry** [piecesofcodecom/punkapocalyptic#11]
There's a 4-leaf clover icon in the upper right corner near chat messages that has tooltips in Portuguese, looks like it's Fortune/Luck related.

On the Character Actor main tab:
The Defense icon tooltip.
Mojo tooltip.
Missions tooltip.
Health tooltip below the token picture.

Inventory tab:
for items Equipped, Ability, and Damage are still in Portuguese.

Background tab:
Type is in Portuguese.
The "Notes and other shit" text is in Portuguese.

**Comment by mrcomac** [comment]
Thank you for the help @sirkerry 

The mentioned ones are fixed in the latest revision, however I just noticed Dialog boxes don't have their texts in the language json files.

Adding below the text for reference to add later.
[in actor sheet](https://github.com/piecesofcodecom/punkapocalyptic/blob/main/module/sheets/actor-sheet.mjs)

Criar item: New Item
Escolha o tipo de item: Choose the item's type
Escolha um atributo: Choose an ability
Modificadores para: Rolagem de atributo ${dataset.label}: Modifiers for: ${dataset.label} Roll
 Complicações / Recursos: Complication / Resources

**Comment by sirkerry** [comment]
> Thank you for the help [@sirkerry](https://github.com/sirkerry)

Thank you for making a FVTT game system for such a cool RPG.

**Comment by sirkerry** [comment]
Okay, I'm making a pass though the Items right now:

**Armor**
There's an "É Bonus?" that I'm not really sure what it's been used for? Maybe to indicate that the armor has a Special property? 

**Background**
Atributo should be Attribute.
In the Atributo dropdown there is a Nenhuma which should be None.
Idiomas should be Languages.
**_Background Items tab_**
+Adicionar should be +Add.
Beneficios da 4a Missao should be Mission 4 Benefits.

**Benefit**
Missoes should be Missions.

**Mutation**
In the Type dropdown there is a Nenhuma which should be None.

**Path**
In the Level dropdown there is a Nenhuma which should be None.
**_Path Benefits tab_**
+Adicionar should be +Add.

**Weapon**
Habilidade should be Ability.
In the Habilidade dropdown there is a Nenhuma which should be None.
In the Category dropdown there is a Nenhuma which should be None.

**Damage Gear popup**
Dano: Weapon window title should be Damage: Weapon
Dados: should be Dice:
Dado: should be Die Type:
Modificador: should be Modifier:
Salvar should be Save

**Comment by sirkerry** [comment]
> Type is in Portuguese.

This is still showing as Tipo on the actor's Background tab.
Other than that minor thing, everything else on the actor sheet looks good.

**Comment by mrcomac** [comment]
@sirkerry 
Yes, i will need to double check actor and item sheets when I'm back home. Currently i don't have access to my PC since. I'll be back from holiday in 3 weeks.

**Comment by mrcomac** [comment]
The new release has more fixes related to language issues.

If you spot any other errors please update this issue.

**Comment by mrcomac** [comment]
I believe English is fully supported now.
